### ISSUE TITLE
look it

### ISSUE THREAD

**Issue by YuGer26** [suyashvash/react-native-loading-modal#3]
we need have dark/light or background

**Comment by suyashvash** [comment]
Thanks for the issue @YuGer26 . I will add a light/dark mode prop and modal style prop also to customize the modal as per need.

**Comment by suyashvash** [comment]
Hey @YuGer26 , I just added support for Dark mode, Modal Style, and Text style for better customizability. Please update and have a look. If you still need something, just let me know!
